services:
  api-factura:
    build: .
    ports:
      - "8002:8002"
    restart: always
    environment:
      MONGO_URI: "mongodb://admin:72942250@35.169.164.120:8006/?authSource=admin"
    networks:
      - internal_network


networks:
  internal_network:
    external: true