services:
  api-factura:
    build: .
    ports:
      - "8002:8002"
    restart: always
    environment:
      MONGO_URI: "mongodb://admin:72942250@172.31.16.52:8006/?authSource=admin"
    networks:
      - internal_network


networks:
  internal_network:
    external: true