version: "3"
services:
  api-factura:
    build: .
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: